### PR TITLE
Updated Telegram.Bot lib to 15.5.1(latest)

### PR DESCRIPTION
**Pull request by Ezergil**

### CODE REVIEW

**Comment by Ezergil** [comment]
@MihaZupan as we discussed : added methods from 15.5.1 (and updated SendPoll and SendInvoice)

also : do we really need public modifier for those?
        public readonly ITelegramBotClient BaseClient;
        public readonly TelegramRequestScheduler RequestScheduler;

**Comment by MihaZupan** [comment]
Thanks!

**Comment by MihaZupan** [comment]
I pushed an update to NuGet

**Comment by Ezergil** [comment]
@MihaZupan cool, thank you! I'm curretly testing telegram threshlolds on Get methods... to bad Telegram has no CorrelationId (e.g. Request id) for responses :)

**Pull request merged**
